version: 4.8.{build}
image: Visual Studio 2019
configuration: Release
install:
- cmd: |
    dotnet restore

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: Sigil.sln
  verbosity: minimal
after_build:
- cmd: >-
    dotnet publish --self-contained false --framework net452

    dotnet publish --self-contained false --framework net462

    dotnet publish --self-contained false --framework net472

    dotnet publish --self-contained false --framework net48

    dotnet publish Sigil --self-contained false --framework netstandard1.5

    dotnet publish Sigil --self-contained false --framework netstandard2.0

    dotnet publish SigilTests --self-contained false --framework netcoreapp1.1

    dotnet publish SigilTests --self-contained false --framework netcoreapp2.2
    
    dotnet pack

- sh: >-
    dotnet publish --self-contained false --framework net452

    dotnet publish --self-contained false --framework net462

    dotnet publish --self-contained false --framework net472

    dotnet publish --self-contained false --framework net48

    dotnet publish Sigil --self-contained false --framework netstandard1.5

    dotnet publish Sigil --self-contained false --framework netstandard2.0

    dotnet publish SigilTests --self-contained false --framework netcoreapp1.1

    dotnet publish SigilTests --self-contained false --framework netcoreapp2.2

    dotnet pack

test_script:
- cmd: dotnet test --no-build --no-restore --logger:Appveyor

artifacts:
- path: '**/*.nupkg'
  name: Nuget
- path: '**/publish/*'
  name: Binaries